SELECT L.ip,
COUNT(L.ip)
AS invalid_count
FROM logs L
GROUP BY L.ip
HAVING (
    CASE WHEN (SELECT COUNT(*) FROM STRING_SPLIT(L.ip,'.')) <> 4 THEN 1 ELSE 0 END 
    +
    CASE WHEN (SELECT COUNT(*) FROM STRING_SPLIT(L.ip,'.') WHERE CAST([VALUE] AS INT) > 255 ) > 0 THEN 1 ELSE 0 END 
    +
    CASE WHEN (SELECT COUNT(*) FROM STRING_SPLIT(L.ip,'.') WHERE [VALUE] LIKE '0%') > 0 THEN 1 ELSE 0 END ) > 0

ORDER BY COUNT(L.ip) DESC, L.ip DESC